#!/bin/sh
grep --color -n -i "$1" */*.{h,cpp} -w
grep --color -n -i "$1" */*/*.{h,cpp} -w | grep -v "protobuf" |grep --color -n "$1" -w
#grep --color -n "$1" base/xlib/*.{h,cpp} -w | grep --color -n "$1" -w
grep --color -n -i "$1" */*/*/*.{h,cpp} -w
grep --color -n -i "$1" Proto/*.proto -w
#grep --color -n "$1" Config/*.xml -w
