<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: ActivityEvent.proto

namespace RO\Cmd {

  class ActivityEventNtfEventCntCmd extends \DrSlump\Protobuf\Message {

    /**  @var int - \RO\Cmd\Command */
    public $cmd = \RO\Cmd\Command::ACTIVITY_EVENT_PROTOCMD;
    
    /**  @var int - \RO\Cmd\ActivityEventParam */
    public $param = \RO\Cmd\ActivityEventParam::ACTIVITYEVENTPARAM_NTF_EVENT_CNT;
    
    /**  @var \RO\Cmd\ActivityEventCnt[]  */
    public $cnt = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.ActivityEventNtfEventCntCmd');

      // OPTIONAL ENUM cmd = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "cmd";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\Command';
      $f->default   = \RO\Cmd\Command::ACTIVITY_EVENT_PROTOCMD;
      $descriptor->addField($f);

      // OPTIONAL ENUM param = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "param";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\ActivityEventParam';
      $f->default   = \RO\Cmd\ActivityEventParam::ACTIVITYEVENTPARAM_NTF_EVENT_CNT;
      $descriptor->addField($f);

      // REPEATED MESSAGE cnt = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "cnt";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\RO\Cmd\ActivityEventCnt';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <cmd> has a value
     *
     * @return boolean
     */
    public function hasCmd(){
      return $this->_has(1);
    }
    
    /**
     * Clear <cmd> value
     *
     * @return \RO\Cmd\ActivityEventNtfEventCntCmd
     */
    public function clearCmd(){
      return $this->_clear(1);
    }
    
    /**
     * Get <cmd> value
     *
     * @return int - \RO\Cmd\Command
     */
    public function getCmd(){
      return $this->_get(1);
    }
    
    /**
     * Set <cmd> value
     *
     * @param int - \RO\Cmd\Command $value
     * @return \RO\Cmd\ActivityEventNtfEventCntCmd
     */
    public function setCmd( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <param> has a value
     *
     * @return boolean
     */
    public function hasParam(){
      return $this->_has(2);
    }
    
    /**
     * Clear <param> value
     *
     * @return \RO\Cmd\ActivityEventNtfEventCntCmd
     */
    public function clearParam(){
      return $this->_clear(2);
    }
    
    /**
     * Get <param> value
     *
     * @return int - \RO\Cmd\ActivityEventParam
     */
    public function getParam(){
      return $this->_get(2);
    }
    
    /**
     * Set <param> value
     *
     * @param int - \RO\Cmd\ActivityEventParam $value
     * @return \RO\Cmd\ActivityEventNtfEventCntCmd
     */
    public function setParam( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <cnt> has a value
     *
     * @return boolean
     */
    public function hasCnt(){
      return $this->_has(3);
    }
    
    /**
     * Clear <cnt> value
     *
     * @return \RO\Cmd\ActivityEventNtfEventCntCmd
     */
    public function clearCnt(){
      return $this->_clear(3);
    }
    
    /**
     * Get <cnt> value
     *
     * @param int $idx
     * @return \RO\Cmd\ActivityEventCnt
     */
    public function getCnt($idx = NULL){
      return $this->_get(3, $idx);
    }
    
    /**
     * Set <cnt> value
     *
     * @param \RO\Cmd\ActivityEventCnt $value
     * @return \RO\Cmd\ActivityEventNtfEventCntCmd
     */
    public function setCnt(\RO\Cmd\ActivityEventCnt $value, $idx = NULL){
      return $this->_set(3, $value, $idx);
    }
    
    /**
     * Get all elements of <cnt>
     *
     * @return \RO\Cmd\ActivityEventCnt[]
     */
    public function getCntList(){
     return $this->_get(3);
    }
    
    /**
     * Add a new element to <cnt>
     *
     * @param \RO\Cmd\ActivityEventCnt $value
     * @return \RO\Cmd\ActivityEventNtfEventCntCmd
     */
    public function addCnt(\RO\Cmd\ActivityEventCnt $value){
     return $this->_add(3, $value);
    }
  }
}

