<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: RecordCmd.proto

namespace RO\Cmd {

  class BlobStage extends \DrSlump\Protobuf\Message {

    /**  @var \RO\Cmd\StageBlobItem[]  */
    public $list = array();
    
    /**  @var int */
    public $resetTime = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.BlobStage');

      // REPEATED MESSAGE list = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "list";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\RO\Cmd\StageBlobItem';
      $descriptor->addField($f);

      // OPTIONAL UINT32 resetTime = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "resetTime";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <list> has a value
     *
     * @return boolean
     */
    public function hasList(){
      return $this->_has(1);
    }
    
    /**
     * Clear <list> value
     *
     * @return \RO\Cmd\BlobStage
     */
    public function clearList(){
      return $this->_clear(1);
    }
    
    /**
     * Get <list> value
     *
     * @param int $idx
     * @return \RO\Cmd\StageBlobItem
     */
    public function getList($idx = NULL){
      return $this->_get(1, $idx);
    }
    
    /**
     * Set <list> value
     *
     * @param \RO\Cmd\StageBlobItem $value
     * @return \RO\Cmd\BlobStage
     */
    public function setList(\RO\Cmd\StageBlobItem $value, $idx = NULL){
      return $this->_set(1, $value, $idx);
    }
    
    /**
     * Get all elements of <list>
     *
     * @return \RO\Cmd\StageBlobItem[]
     */
    public function getListList(){
     return $this->_get(1);
    }
    
    /**
     * Add a new element to <list>
     *
     * @param \RO\Cmd\StageBlobItem $value
     * @return \RO\Cmd\BlobStage
     */
    public function addList(\RO\Cmd\StageBlobItem $value){
     return $this->_add(1, $value);
    }
    
    /**
     * Check if <resetTime> has a value
     *
     * @return boolean
     */
    public function hasResetTime(){
      return $this->_has(2);
    }
    
    /**
     * Clear <resetTime> value
     *
     * @return \RO\Cmd\BlobStage
     */
    public function clearResetTime(){
      return $this->_clear(2);
    }
    
    /**
     * Get <resetTime> value
     *
     * @return int
     */
    public function getResetTime(){
      return $this->_get(2);
    }
    
    /**
     * Set <resetTime> value
     *
     * @param int $value
     * @return \RO\Cmd\BlobStage
     */
    public function setResetTime( $value){
      return $this->_set(2, $value);
    }
  }
}

