<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: SceneUser2.proto

namespace RO\Cmd {

  class EFuncMapType extends \DrSlump\Protobuf\Enum {
    const EFUNCMAPTYPE_POLLY = 1;
  }
}
