<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: WeddingCCmd.proto

namespace RO\Cmd {

  class EGiveUpType extends \DrSlump\Protobuf\Enum {
    const EGiveUpType_Together = 1;
    const EGiveUpType_Single = 2;
    const EGiveUpType_Force = 3;
    const EGiveUpType_DelChar = 4;
  }
}
