<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: FuBenCmd.proto

namespace RO\Cmd {

  class EGuildGateState extends \DrSlump\Protobuf\Enum {
    const EGUILDGATESTATE_MIN = 0;
    const EGUILDGATESTATE_LOCK = 1;
    const EGUILDGATESTATE_CLOSE = 2;
    const EGUILDGATESTATE_OPEN = 3;
  }
}
