<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: SceneUser2.proto

namespace RO\Cmd {

  class ERenameErrCode extends \DrSlump\Protobuf\Enum {
    const ERENAME_SUCCESS = 0;
    const ERENAME_CD = 1;
    const ERENAME_CONFLICT = 2;
  }
}
