<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: SessionSociality.proto

namespace RO\Cmd {

  class ESocialData extends \DrSlump\Protobuf\Enum {
    const ESOCIALDATA_MIN = 1;
    const ESOCIALDATA_LEVEL = 2;
    const ESOCIALDATA_OFFLINETIME = 3;
    const ESOCIALDATA_RELATION = 4;
    const ESOCIALDATA_PROFESSION = 5;
    const ESOCIALDATA_PORTRAIT = 6;
    const ESOCIALDATA_FRAME = 7;
    const ESOCIALDATA_HAIR = 8;
    const ESOCIALDATA_HAIRCOLOR = 9;
    const ESOCIALDATA_BODY = 10;
    const ESOCIALDATA_ADVENTURELV = 11;
    const ESOCIALDATA_ADVENTUREEXP = 12;
    const ESOCIALDATA_APPELLATION = 13;
    const ESOCIALDATA_GENDER = 14;
    const ESOCIALDATA_GUILDNAME = 15;
    const ESOCIALDATA_GUILDPORTRAIT = 16;
    const ESOCIALDATA_BLINK = 18;
    const ESOCIALDATA_ZONEID = 19;
    const ESOCIALDATA_NAME = 20;
    const ESOCIALDATA_CREATETIME = 21;
    const ESOCIALDATA_HEAD = 22;
    const ESOCIALDATA_FACE = 23;
    const ESOCIALDATA_MOUTH = 24;
    const ESOCIALDATA_TUTOR_PROFIC = 25;
    const ESOCIALDATA_EYE = 26;
    const ESOCIALDATA_RECALL = 27;
    const ESOCIALDATA_CANRECALL = 28;
    const ESOCIALDATA_MAX = 29;
  }
}
