<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: SceneTip.proto

namespace RO\Cmd {

  class ETipItemOpt extends \DrSlump\Protobuf\Enum {
    const ETIPITEMOPT_ADD = 1;
    const ETIPITEMOPT_DELETE = 2;
  }
}
