<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: StatCmd.proto

namespace RO\Cmd {

  class ETradeListType extends \DrSlump\Protobuf\Enum {
    const ETRADE_ITEM_INFO = 1;
    const ETRADE_PENDING_LIST = 2;
    const ETRADE_SALED_LIST = 3;
    const ETRADE_BUYED_LIST = 4;
  }
}
