<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: SceneFood.proto

namespace RO\Cmd {

  class FoodInfoNtf extends \DrSlump\Protobuf\Message {

    /**  @var int - \RO\Cmd\Command */
    public $cmd = \RO\Cmd\Command::SCENE_USER_FOOD_PROTOCMD;
    
    /**  @var int - \RO\Cmd\FoodParam */
    public $param = \RO\Cmd\FoodParam::FOODPARAM_FOOD_INFO_NTF;
    
    /**  @var int[]  */
    public $recipeids = array();
    
    /**  @var int[]  */
    public $last_cooked_foods = array();
    
    /**  @var \RO\Cmd\FoodItemInfo2[]  */
    public $eat_foods = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.FoodInfoNtf');

      // OPTIONAL ENUM cmd = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "cmd";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\Command';
      $f->default   = \RO\Cmd\Command::SCENE_USER_FOOD_PROTOCMD;
      $descriptor->addField($f);

      // OPTIONAL ENUM param = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "param";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\FoodParam';
      $f->default   = \RO\Cmd\FoodParam::FOODPARAM_FOOD_INFO_NTF;
      $descriptor->addField($f);

      // REPEATED UINT32 recipeids = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "recipeids";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      // REPEATED UINT32 last_cooked_foods = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "last_cooked_foods";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      // REPEATED MESSAGE eat_foods = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "eat_foods";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\RO\Cmd\FoodItemInfo2';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <cmd> has a value
     *
     * @return boolean
     */
    public function hasCmd(){
      return $this->_has(1);
    }
    
    /**
     * Clear <cmd> value
     *
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function clearCmd(){
      return $this->_clear(1);
    }
    
    /**
     * Get <cmd> value
     *
     * @return int - \RO\Cmd\Command
     */
    public function getCmd(){
      return $this->_get(1);
    }
    
    /**
     * Set <cmd> value
     *
     * @param int - \RO\Cmd\Command $value
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function setCmd( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <param> has a value
     *
     * @return boolean
     */
    public function hasParam(){
      return $this->_has(2);
    }
    
    /**
     * Clear <param> value
     *
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function clearParam(){
      return $this->_clear(2);
    }
    
    /**
     * Get <param> value
     *
     * @return int - \RO\Cmd\FoodParam
     */
    public function getParam(){
      return $this->_get(2);
    }
    
    /**
     * Set <param> value
     *
     * @param int - \RO\Cmd\FoodParam $value
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function setParam( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <recipeids> has a value
     *
     * @return boolean
     */
    public function hasRecipeids(){
      return $this->_has(3);
    }
    
    /**
     * Clear <recipeids> value
     *
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function clearRecipeids(){
      return $this->_clear(3);
    }
    
    /**
     * Get <recipeids> value
     *
     * @param int $idx
     * @return int
     */
    public function getRecipeids($idx = NULL){
      return $this->_get(3, $idx);
    }
    
    /**
     * Set <recipeids> value
     *
     * @param int $value
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function setRecipeids( $value, $idx = NULL){
      return $this->_set(3, $value, $idx);
    }
    
    /**
     * Get all elements of <recipeids>
     *
     * @return int[]
     */
    public function getRecipeidsList(){
     return $this->_get(3);
    }
    
    /**
     * Add a new element to <recipeids>
     *
     * @param int $value
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function addRecipeids( $value){
     return $this->_add(3, $value);
    }
    
    /**
     * Check if <last_cooked_foods> has a value
     *
     * @return boolean
     */
    public function hasLastCookedFoods(){
      return $this->_has(4);
    }
    
    /**
     * Clear <last_cooked_foods> value
     *
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function clearLastCookedFoods(){
      return $this->_clear(4);
    }
    
    /**
     * Get <last_cooked_foods> value
     *
     * @param int $idx
     * @return int
     */
    public function getLastCookedFoods($idx = NULL){
      return $this->_get(4, $idx);
    }
    
    /**
     * Set <last_cooked_foods> value
     *
     * @param int $value
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function setLastCookedFoods( $value, $idx = NULL){
      return $this->_set(4, $value, $idx);
    }
    
    /**
     * Get all elements of <last_cooked_foods>
     *
     * @return int[]
     */
    public function getLastCookedFoodsList(){
     return $this->_get(4);
    }
    
    /**
     * Add a new element to <last_cooked_foods>
     *
     * @param int $value
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function addLastCookedFoods( $value){
     return $this->_add(4, $value);
    }
    
    /**
     * Check if <eat_foods> has a value
     *
     * @return boolean
     */
    public function hasEatFoods(){
      return $this->_has(5);
    }
    
    /**
     * Clear <eat_foods> value
     *
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function clearEatFoods(){
      return $this->_clear(5);
    }
    
    /**
     * Get <eat_foods> value
     *
     * @param int $idx
     * @return \RO\Cmd\FoodItemInfo2
     */
    public function getEatFoods($idx = NULL){
      return $this->_get(5, $idx);
    }
    
    /**
     * Set <eat_foods> value
     *
     * @param \RO\Cmd\FoodItemInfo2 $value
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function setEatFoods(\RO\Cmd\FoodItemInfo2 $value, $idx = NULL){
      return $this->_set(5, $value, $idx);
    }
    
    /**
     * Get all elements of <eat_foods>
     *
     * @return \RO\Cmd\FoodItemInfo2[]
     */
    public function getEatFoodsList(){
     return $this->_get(5);
    }
    
    /**
     * Add a new element to <eat_foods>
     *
     * @param \RO\Cmd\FoodItemInfo2 $value
     * @return \RO\Cmd\FoodInfoNtf
     */
    public function addEatFoods(\RO\Cmd\FoodItemInfo2 $value){
     return $this->_add(5, $value);
    }
  }
}

