<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: SceneMap.proto

namespace RO\Cmd {

  class LineData extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $masterId = null;
    
    /**  @var int */
    public $slaveId = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.LineData');

      // OPTIONAL UINT64 masterId = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "masterId";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL UINT64 slaveId = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "slaveId";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <masterId> has a value
     *
     * @return boolean
     */
    public function hasMasterId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <masterId> value
     *
     * @return \RO\Cmd\LineData
     */
    public function clearMasterId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <masterId> value
     *
     * @return int
     */
    public function getMasterId(){
      return $this->_get(1);
    }
    
    /**
     * Set <masterId> value
     *
     * @param int $value
     * @return \RO\Cmd\LineData
     */
    public function setMasterId( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <slaveId> has a value
     *
     * @return boolean
     */
    public function hasSlaveId(){
      return $this->_has(2);
    }
    
    /**
     * Clear <slaveId> value
     *
     * @return \RO\Cmd\LineData
     */
    public function clearSlaveId(){
      return $this->_clear(2);
    }
    
    /**
     * Get <slaveId> value
     *
     * @return int
     */
    public function getSlaveId(){
      return $this->_get(2);
    }
    
    /**
     * Set <slaveId> value
     *
     * @param int $value
     * @return \RO\Cmd\LineData
     */
    public function setSlaveId( $value){
      return $this->_set(2, $value);
    }
  }
}

