<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: FuBenCmd.proto

namespace RO\Cmd {

  class QueryGvgTowerInfoFubenCmd extends \DrSlump\Protobuf\Message {

    /**  @var int - \RO\Cmd\Command */
    public $cmd = \RO\Cmd\Command::FUBEN_PROTOCMD;
    
    /**  @var int - \RO\Cmd\FuBenParam */
    public $param = \RO\Cmd\FuBenParam::SUPERGVG_QUERY_TOWERINFO;
    
    /**  @var int - \RO\Cmd\EGvgTowerType */
    public $etype = null;
    
    /**  @var boolean */
    public $open = false;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.QueryGvgTowerInfoFubenCmd');

      // OPTIONAL ENUM cmd = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "cmd";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\Command';
      $f->default   = \RO\Cmd\Command::FUBEN_PROTOCMD;
      $descriptor->addField($f);

      // OPTIONAL ENUM param = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "param";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\FuBenParam';
      $f->default   = \RO\Cmd\FuBenParam::SUPERGVG_QUERY_TOWERINFO;
      $descriptor->addField($f);

      // REQUIRED ENUM etype = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "etype";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $f->reference = '\RO\Cmd\EGvgTowerType';
      $descriptor->addField($f);

      // OPTIONAL BOOL open = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "open";
      $f->type      = \DrSlump\Protobuf::TYPE_BOOL;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->default   = false;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <cmd> has a value
     *
     * @return boolean
     */
    public function hasCmd(){
      return $this->_has(1);
    }
    
    /**
     * Clear <cmd> value
     *
     * @return \RO\Cmd\QueryGvgTowerInfoFubenCmd
     */
    public function clearCmd(){
      return $this->_clear(1);
    }
    
    /**
     * Get <cmd> value
     *
     * @return int - \RO\Cmd\Command
     */
    public function getCmd(){
      return $this->_get(1);
    }
    
    /**
     * Set <cmd> value
     *
     * @param int - \RO\Cmd\Command $value
     * @return \RO\Cmd\QueryGvgTowerInfoFubenCmd
     */
    public function setCmd( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <param> has a value
     *
     * @return boolean
     */
    public function hasParam(){
      return $this->_has(2);
    }
    
    /**
     * Clear <param> value
     *
     * @return \RO\Cmd\QueryGvgTowerInfoFubenCmd
     */
    public function clearParam(){
      return $this->_clear(2);
    }
    
    /**
     * Get <param> value
     *
     * @return int - \RO\Cmd\FuBenParam
     */
    public function getParam(){
      return $this->_get(2);
    }
    
    /**
     * Set <param> value
     *
     * @param int - \RO\Cmd\FuBenParam $value
     * @return \RO\Cmd\QueryGvgTowerInfoFubenCmd
     */
    public function setParam( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <etype> has a value
     *
     * @return boolean
     */
    public function hasEtype(){
      return $this->_has(3);
    }
    
    /**
     * Clear <etype> value
     *
     * @return \RO\Cmd\QueryGvgTowerInfoFubenCmd
     */
    public function clearEtype(){
      return $this->_clear(3);
    }
    
    /**
     * Get <etype> value
     *
     * @return int - \RO\Cmd\EGvgTowerType
     */
    public function getEtype(){
      return $this->_get(3);
    }
    
    /**
     * Set <etype> value
     *
     * @param int - \RO\Cmd\EGvgTowerType $value
     * @return \RO\Cmd\QueryGvgTowerInfoFubenCmd
     */
    public function setEtype( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <open> has a value
     *
     * @return boolean
     */
    public function hasOpen(){
      return $this->_has(4);
    }
    
    /**
     * Clear <open> value
     *
     * @return \RO\Cmd\QueryGvgTowerInfoFubenCmd
     */
    public function clearOpen(){
      return $this->_clear(4);
    }
    
    /**
     * Get <open> value
     *
     * @return boolean
     */
    public function getOpen(){
      return $this->_get(4);
    }
    
    /**
     * Set <open> value
     *
     * @param boolean $value
     * @return \RO\Cmd\QueryGvgTowerInfoFubenCmd
     */
    public function setOpen( $value){
      return $this->_set(4, $value);
    }
  }
}

