<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: SessionShop.proto

namespace RO\Cmd {

  class QueryShopConfigCmd extends \DrSlump\Protobuf\Message {

    /**  @var int - \RO\Cmd\Command */
    public $cmd = \RO\Cmd\Command::SESSION_USER_SHOP_PROTOCMD;
    
    /**  @var int - \RO\Cmd\ShopParam */
    public $param = \RO\Cmd\ShopParam::SHOPPARAM_QUERY_SHOP_CONFIG;
    
    /**  @var int */
    public $type = null;
    
    /**  @var int */
    public $shopid = null;
    
    /**  @var \RO\Cmd\ShopItem[]  */
    public $goods = array();
    
    /**  @var int */
    public $screen = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.QueryShopConfigCmd');

      // OPTIONAL ENUM cmd = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "cmd";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\Command';
      $f->default   = \RO\Cmd\Command::SESSION_USER_SHOP_PROTOCMD;
      $descriptor->addField($f);

      // OPTIONAL ENUM param = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "param";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\ShopParam';
      $f->default   = \RO\Cmd\ShopParam::SHOPPARAM_QUERY_SHOP_CONFIG;
      $descriptor->addField($f);

      // OPTIONAL UINT32 type = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "type";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL UINT32 shopid = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "shopid";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED MESSAGE goods = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "goods";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\RO\Cmd\ShopItem';
      $descriptor->addField($f);

      // OPTIONAL UINT32 screen = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "screen";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <cmd> has a value
     *
     * @return boolean
     */
    public function hasCmd(){
      return $this->_has(1);
    }
    
    /**
     * Clear <cmd> value
     *
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function clearCmd(){
      return $this->_clear(1);
    }
    
    /**
     * Get <cmd> value
     *
     * @return int - \RO\Cmd\Command
     */
    public function getCmd(){
      return $this->_get(1);
    }
    
    /**
     * Set <cmd> value
     *
     * @param int - \RO\Cmd\Command $value
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function setCmd( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <param> has a value
     *
     * @return boolean
     */
    public function hasParam(){
      return $this->_has(2);
    }
    
    /**
     * Clear <param> value
     *
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function clearParam(){
      return $this->_clear(2);
    }
    
    /**
     * Get <param> value
     *
     * @return int - \RO\Cmd\ShopParam
     */
    public function getParam(){
      return $this->_get(2);
    }
    
    /**
     * Set <param> value
     *
     * @param int - \RO\Cmd\ShopParam $value
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function setParam( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <type> has a value
     *
     * @return boolean
     */
    public function hasType(){
      return $this->_has(3);
    }
    
    /**
     * Clear <type> value
     *
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function clearType(){
      return $this->_clear(3);
    }
    
    /**
     * Get <type> value
     *
     * @return int
     */
    public function getType(){
      return $this->_get(3);
    }
    
    /**
     * Set <type> value
     *
     * @param int $value
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function setType( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <shopid> has a value
     *
     * @return boolean
     */
    public function hasShopid(){
      return $this->_has(4);
    }
    
    /**
     * Clear <shopid> value
     *
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function clearShopid(){
      return $this->_clear(4);
    }
    
    /**
     * Get <shopid> value
     *
     * @return int
     */
    public function getShopid(){
      return $this->_get(4);
    }
    
    /**
     * Set <shopid> value
     *
     * @param int $value
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function setShopid( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <goods> has a value
     *
     * @return boolean
     */
    public function hasGoods(){
      return $this->_has(5);
    }
    
    /**
     * Clear <goods> value
     *
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function clearGoods(){
      return $this->_clear(5);
    }
    
    /**
     * Get <goods> value
     *
     * @param int $idx
     * @return \RO\Cmd\ShopItem
     */
    public function getGoods($idx = NULL){
      return $this->_get(5, $idx);
    }
    
    /**
     * Set <goods> value
     *
     * @param \RO\Cmd\ShopItem $value
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function setGoods(\RO\Cmd\ShopItem $value, $idx = NULL){
      return $this->_set(5, $value, $idx);
    }
    
    /**
     * Get all elements of <goods>
     *
     * @return \RO\Cmd\ShopItem[]
     */
    public function getGoodsList(){
     return $this->_get(5);
    }
    
    /**
     * Add a new element to <goods>
     *
     * @param \RO\Cmd\ShopItem $value
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function addGoods(\RO\Cmd\ShopItem $value){
     return $this->_add(5, $value);
    }
    
    /**
     * Check if <screen> has a value
     *
     * @return boolean
     */
    public function hasScreen(){
      return $this->_has(6);
    }
    
    /**
     * Clear <screen> value
     *
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function clearScreen(){
      return $this->_clear(6);
    }
    
    /**
     * Get <screen> value
     *
     * @return int
     */
    public function getScreen(){
      return $this->_get(6);
    }
    
    /**
     * Set <screen> value
     *
     * @param int $value
     * @return \RO\Cmd\QueryShopConfigCmd
     */
    public function setScreen( $value){
      return $this->_set(6, $value);
    }
  }
}

