<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: SceneQuest.proto

namespace RO\Cmd {

  class QuestStep extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $process = 0;
    
    /**  @var int[]  */
    public $params = array();
    
    /**  @var string[]  */
    public $names = array();
    
    /**  @var \RO\Cmd\QuestPConfig */
    public $config = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.QuestStep');

      // OPTIONAL UINT32 process = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "process";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->default   = 0;
      $descriptor->addField($f);

      // REPEATED UINT64 params = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "params";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      // REPEATED STRING names = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "names";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE config = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "config";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\QuestPConfig';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <process> has a value
     *
     * @return boolean
     */
    public function hasProcess(){
      return $this->_has(1);
    }
    
    /**
     * Clear <process> value
     *
     * @return \RO\Cmd\QuestStep
     */
    public function clearProcess(){
      return $this->_clear(1);
    }
    
    /**
     * Get <process> value
     *
     * @return int
     */
    public function getProcess(){
      return $this->_get(1);
    }
    
    /**
     * Set <process> value
     *
     * @param int $value
     * @return \RO\Cmd\QuestStep
     */
    public function setProcess( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <params> has a value
     *
     * @return boolean
     */
    public function hasParams(){
      return $this->_has(2);
    }
    
    /**
     * Clear <params> value
     *
     * @return \RO\Cmd\QuestStep
     */
    public function clearParams(){
      return $this->_clear(2);
    }
    
    /**
     * Get <params> value
     *
     * @param int $idx
     * @return int
     */
    public function getParams($idx = NULL){
      return $this->_get(2, $idx);
    }
    
    /**
     * Set <params> value
     *
     * @param int $value
     * @return \RO\Cmd\QuestStep
     */
    public function setParams( $value, $idx = NULL){
      return $this->_set(2, $value, $idx);
    }
    
    /**
     * Get all elements of <params>
     *
     * @return int[]
     */
    public function getParamsList(){
     return $this->_get(2);
    }
    
    /**
     * Add a new element to <params>
     *
     * @param int $value
     * @return \RO\Cmd\QuestStep
     */
    public function addParams( $value){
     return $this->_add(2, $value);
    }
    
    /**
     * Check if <names> has a value
     *
     * @return boolean
     */
    public function hasNames(){
      return $this->_has(3);
    }
    
    /**
     * Clear <names> value
     *
     * @return \RO\Cmd\QuestStep
     */
    public function clearNames(){
      return $this->_clear(3);
    }
    
    /**
     * Get <names> value
     *
     * @param int $idx
     * @return string
     */
    public function getNames($idx = NULL){
      return $this->_get(3, $idx);
    }
    
    /**
     * Set <names> value
     *
     * @param string $value
     * @return \RO\Cmd\QuestStep
     */
    public function setNames( $value, $idx = NULL){
      return $this->_set(3, $value, $idx);
    }
    
    /**
     * Get all elements of <names>
     *
     * @return string[]
     */
    public function getNamesList(){
     return $this->_get(3);
    }
    
    /**
     * Add a new element to <names>
     *
     * @param string $value
     * @return \RO\Cmd\QuestStep
     */
    public function addNames( $value){
     return $this->_add(3, $value);
    }
    
    /**
     * Check if <config> has a value
     *
     * @return boolean
     */
    public function hasConfig(){
      return $this->_has(4);
    }
    
    /**
     * Clear <config> value
     *
     * @return \RO\Cmd\QuestStep
     */
    public function clearConfig(){
      return $this->_clear(4);
    }
    
    /**
     * Get <config> value
     *
     * @return \RO\Cmd\QuestPConfig
     */
    public function getConfig(){
      return $this->_get(4);
    }
    
    /**
     * Set <config> value
     *
     * @param \RO\Cmd\QuestPConfig $value
     * @return \RO\Cmd\QuestStep
     */
    public function setConfig(\RO\Cmd\QuestPConfig $value){
      return $this->_set(4, $value);
    }
  }
}

