<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: SceneTrade.proto

namespace RO\Cmd {

  class ReduceMoneyRecordTradeCmd extends \DrSlump\Protobuf\Message {

    /**  @var int - \RO\Cmd\Command */
    public $cmd = \RO\Cmd\Command::TRADE_PROTOCMD;
    
    /**  @var int - \RO\Cmd\RecordServerTradeParam */
    public $param = \RO\Cmd\RecordServerTradeParam::REDUCE_MONEY_RECORDTRADE;
    
    /**  @var int */
    public $money_type = null;
    
    /**  @var int */
    public $total_money = null;
    
    /**  @var int - \RO\Cmd\ETRADE_RET_CODE */
    public $ret = null;
    
    /**  @var int */
    public $charid = null;
    
    /**  @var \RO\Cmd\TradeItemBaseInfo */
    public $item_info = null;
    
    /**  @var int */
    public $quota = 0;
    
    /**  @var int - \RO\Cmd\ETradeType */
    public $type = \RO\Cmd\ETradeType::ETRADETYPE_TRADE;
    
    /**  @var int */
    public $record_id = 0;
    
    /**  @var int */
    public $lock_quota = 0;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.ReduceMoneyRecordTradeCmd');

      // OPTIONAL ENUM cmd = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "cmd";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\Command';
      $f->default   = \RO\Cmd\Command::TRADE_PROTOCMD;
      $descriptor->addField($f);

      // OPTIONAL ENUM param = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "param";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\RecordServerTradeParam';
      $f->default   = \RO\Cmd\RecordServerTradeParam::REDUCE_MONEY_RECORDTRADE;
      $descriptor->addField($f);

      // OPTIONAL UINT32 money_type = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "money_type";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL UINT32 total_money = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "total_money";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL ENUM ret = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "ret";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\ETRADE_RET_CODE';
      $descriptor->addField($f);

      // OPTIONAL UINT64 charid = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "charid";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL MESSAGE item_info = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "item_info";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\TradeItemBaseInfo';
      $descriptor->addField($f);

      // OPTIONAL UINT64 quota = 8
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 8;
      $f->name      = "quota";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->default   = 0;
      $descriptor->addField($f);

      // OPTIONAL ENUM type = 9
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 9;
      $f->name      = "type";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\ETradeType';
      $f->default   = \RO\Cmd\ETradeType::ETRADETYPE_TRADE;
      $descriptor->addField($f);

      // OPTIONAL UINT64 record_id = 10
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 10;
      $f->name      = "record_id";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->default   = 0;
      $descriptor->addField($f);

      // OPTIONAL UINT64 lock_quota = 11
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 11;
      $f->name      = "lock_quota";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->default   = 0;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <cmd> has a value
     *
     * @return boolean
     */
    public function hasCmd(){
      return $this->_has(1);
    }
    
    /**
     * Clear <cmd> value
     *
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function clearCmd(){
      return $this->_clear(1);
    }
    
    /**
     * Get <cmd> value
     *
     * @return int - \RO\Cmd\Command
     */
    public function getCmd(){
      return $this->_get(1);
    }
    
    /**
     * Set <cmd> value
     *
     * @param int - \RO\Cmd\Command $value
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function setCmd( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <param> has a value
     *
     * @return boolean
     */
    public function hasParam(){
      return $this->_has(2);
    }
    
    /**
     * Clear <param> value
     *
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function clearParam(){
      return $this->_clear(2);
    }
    
    /**
     * Get <param> value
     *
     * @return int - \RO\Cmd\RecordServerTradeParam
     */
    public function getParam(){
      return $this->_get(2);
    }
    
    /**
     * Set <param> value
     *
     * @param int - \RO\Cmd\RecordServerTradeParam $value
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function setParam( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <money_type> has a value
     *
     * @return boolean
     */
    public function hasMoneyType(){
      return $this->_has(3);
    }
    
    /**
     * Clear <money_type> value
     *
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function clearMoneyType(){
      return $this->_clear(3);
    }
    
    /**
     * Get <money_type> value
     *
     * @return int
     */
    public function getMoneyType(){
      return $this->_get(3);
    }
    
    /**
     * Set <money_type> value
     *
     * @param int $value
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function setMoneyType( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <total_money> has a value
     *
     * @return boolean
     */
    public function hasTotalMoney(){
      return $this->_has(4);
    }
    
    /**
     * Clear <total_money> value
     *
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function clearTotalMoney(){
      return $this->_clear(4);
    }
    
    /**
     * Get <total_money> value
     *
     * @return int
     */
    public function getTotalMoney(){
      return $this->_get(4);
    }
    
    /**
     * Set <total_money> value
     *
     * @param int $value
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function setTotalMoney( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <ret> has a value
     *
     * @return boolean
     */
    public function hasRet(){
      return $this->_has(5);
    }
    
    /**
     * Clear <ret> value
     *
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function clearRet(){
      return $this->_clear(5);
    }
    
    /**
     * Get <ret> value
     *
     * @return int - \RO\Cmd\ETRADE_RET_CODE
     */
    public function getRet(){
      return $this->_get(5);
    }
    
    /**
     * Set <ret> value
     *
     * @param int - \RO\Cmd\ETRADE_RET_CODE $value
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function setRet( $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <charid> has a value
     *
     * @return boolean
     */
    public function hasCharid(){
      return $this->_has(6);
    }
    
    /**
     * Clear <charid> value
     *
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function clearCharid(){
      return $this->_clear(6);
    }
    
    /**
     * Get <charid> value
     *
     * @return int
     */
    public function getCharid(){
      return $this->_get(6);
    }
    
    /**
     * Set <charid> value
     *
     * @param int $value
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function setCharid( $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <item_info> has a value
     *
     * @return boolean
     */
    public function hasItemInfo(){
      return $this->_has(7);
    }
    
    /**
     * Clear <item_info> value
     *
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function clearItemInfo(){
      return $this->_clear(7);
    }
    
    /**
     * Get <item_info> value
     *
     * @return \RO\Cmd\TradeItemBaseInfo
     */
    public function getItemInfo(){
      return $this->_get(7);
    }
    
    /**
     * Set <item_info> value
     *
     * @param \RO\Cmd\TradeItemBaseInfo $value
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function setItemInfo(\RO\Cmd\TradeItemBaseInfo $value){
      return $this->_set(7, $value);
    }
    
    /**
     * Check if <quota> has a value
     *
     * @return boolean
     */
    public function hasQuota(){
      return $this->_has(8);
    }
    
    /**
     * Clear <quota> value
     *
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function clearQuota(){
      return $this->_clear(8);
    }
    
    /**
     * Get <quota> value
     *
     * @return int
     */
    public function getQuota(){
      return $this->_get(8);
    }
    
    /**
     * Set <quota> value
     *
     * @param int $value
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function setQuota( $value){
      return $this->_set(8, $value);
    }
    
    /**
     * Check if <type> has a value
     *
     * @return boolean
     */
    public function hasType(){
      return $this->_has(9);
    }
    
    /**
     * Clear <type> value
     *
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function clearType(){
      return $this->_clear(9);
    }
    
    /**
     * Get <type> value
     *
     * @return int - \RO\Cmd\ETradeType
     */
    public function getType(){
      return $this->_get(9);
    }
    
    /**
     * Set <type> value
     *
     * @param int - \RO\Cmd\ETradeType $value
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function setType( $value){
      return $this->_set(9, $value);
    }
    
    /**
     * Check if <record_id> has a value
     *
     * @return boolean
     */
    public function hasRecordId(){
      return $this->_has(10);
    }
    
    /**
     * Clear <record_id> value
     *
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function clearRecordId(){
      return $this->_clear(10);
    }
    
    /**
     * Get <record_id> value
     *
     * @return int
     */
    public function getRecordId(){
      return $this->_get(10);
    }
    
    /**
     * Set <record_id> value
     *
     * @param int $value
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function setRecordId( $value){
      return $this->_set(10, $value);
    }
    
    /**
     * Check if <lock_quota> has a value
     *
     * @return boolean
     */
    public function hasLockQuota(){
      return $this->_has(11);
    }
    
    /**
     * Clear <lock_quota> value
     *
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function clearLockQuota(){
      return $this->_clear(11);
    }
    
    /**
     * Get <lock_quota> value
     *
     * @return int
     */
    public function getLockQuota(){
      return $this->_get(11);
    }
    
    /**
     * Set <lock_quota> value
     *
     * @param int $value
     * @return \RO\Cmd\ReduceMoneyRecordTradeCmd
     */
    public function setLockQuota( $value){
      return $this->_set(11, $value);
    }
  }
}

