<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: SceneItem.proto

namespace RO\Cmd {

  class ReqQuotaDetailCmd extends \DrSlump\Protobuf\Message {

    /**  @var int - \RO\Cmd\Command */
    public $cmd = \RO\Cmd\Command::SCENE_USER_ITEM_PROTOCMD;
    
    /**  @var int - \RO\Cmd\ItemParam */
    public $param = \RO\Cmd\ItemParam::ITEMPARAM_REQ_QUOTA_DETAIL;
    
    /**  @var int */
    public $page_index = null;
    
    /**  @var \RO\Cmd\QuotaDetail[]  */
    public $detail = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.ReqQuotaDetailCmd');

      // OPTIONAL ENUM cmd = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "cmd";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\Command';
      $f->default   = \RO\Cmd\Command::SCENE_USER_ITEM_PROTOCMD;
      $descriptor->addField($f);

      // OPTIONAL ENUM param = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "param";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\ItemParam';
      $f->default   = \RO\Cmd\ItemParam::ITEMPARAM_REQ_QUOTA_DETAIL;
      $descriptor->addField($f);

      // OPTIONAL UINT32 page_index = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "page_index";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED MESSAGE detail = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "detail";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\RO\Cmd\QuotaDetail';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <cmd> has a value
     *
     * @return boolean
     */
    public function hasCmd(){
      return $this->_has(1);
    }
    
    /**
     * Clear <cmd> value
     *
     * @return \RO\Cmd\ReqQuotaDetailCmd
     */
    public function clearCmd(){
      return $this->_clear(1);
    }
    
    /**
     * Get <cmd> value
     *
     * @return int - \RO\Cmd\Command
     */
    public function getCmd(){
      return $this->_get(1);
    }
    
    /**
     * Set <cmd> value
     *
     * @param int - \RO\Cmd\Command $value
     * @return \RO\Cmd\ReqQuotaDetailCmd
     */
    public function setCmd( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <param> has a value
     *
     * @return boolean
     */
    public function hasParam(){
      return $this->_has(2);
    }
    
    /**
     * Clear <param> value
     *
     * @return \RO\Cmd\ReqQuotaDetailCmd
     */
    public function clearParam(){
      return $this->_clear(2);
    }
    
    /**
     * Get <param> value
     *
     * @return int - \RO\Cmd\ItemParam
     */
    public function getParam(){
      return $this->_get(2);
    }
    
    /**
     * Set <param> value
     *
     * @param int - \RO\Cmd\ItemParam $value
     * @return \RO\Cmd\ReqQuotaDetailCmd
     */
    public function setParam( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <page_index> has a value
     *
     * @return boolean
     */
    public function hasPageIndex(){
      return $this->_has(3);
    }
    
    /**
     * Clear <page_index> value
     *
     * @return \RO\Cmd\ReqQuotaDetailCmd
     */
    public function clearPageIndex(){
      return $this->_clear(3);
    }
    
    /**
     * Get <page_index> value
     *
     * @return int
     */
    public function getPageIndex(){
      return $this->_get(3);
    }
    
    /**
     * Set <page_index> value
     *
     * @param int $value
     * @return \RO\Cmd\ReqQuotaDetailCmd
     */
    public function setPageIndex( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <detail> has a value
     *
     * @return boolean
     */
    public function hasDetail(){
      return $this->_has(4);
    }
    
    /**
     * Clear <detail> value
     *
     * @return \RO\Cmd\ReqQuotaDetailCmd
     */
    public function clearDetail(){
      return $this->_clear(4);
    }
    
    /**
     * Get <detail> value
     *
     * @param int $idx
     * @return \RO\Cmd\QuotaDetail
     */
    public function getDetail($idx = NULL){
      return $this->_get(4, $idx);
    }
    
    /**
     * Set <detail> value
     *
     * @param \RO\Cmd\QuotaDetail $value
     * @return \RO\Cmd\ReqQuotaDetailCmd
     */
    public function setDetail(\RO\Cmd\QuotaDetail $value, $idx = NULL){
      return $this->_set(4, $value, $idx);
    }
    
    /**
     * Get all elements of <detail>
     *
     * @return \RO\Cmd\QuotaDetail[]
     */
    public function getDetailList(){
     return $this->_get(4);
    }
    
    /**
     * Add a new element to <detail>
     *
     * @param \RO\Cmd\QuotaDetail $value
     * @return \RO\Cmd\ReqQuotaDetailCmd
     */
    public function addDetail(\RO\Cmd\QuotaDetail $value){
     return $this->_add(4, $value);
    }
  }
}

