<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: ProtoCommon.proto

namespace RO\Cmd {

  class SpEffectData extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $guid = null;
    
    /**  @var int */
    public $id = null;
    
    /**  @var int[]  */
    public $entity = array();
    
    /**  @var int */
    public $expiretime = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.SpEffectData');

      // OPTIONAL STRING guid = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "guid";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL UINT32 id = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "id";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED UINT64 entity = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "entity";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      // OPTIONAL UINT32 expiretime = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "expiretime";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <guid> has a value
     *
     * @return boolean
     */
    public function hasGuid(){
      return $this->_has(1);
    }
    
    /**
     * Clear <guid> value
     *
     * @return \RO\Cmd\SpEffectData
     */
    public function clearGuid(){
      return $this->_clear(1);
    }
    
    /**
     * Get <guid> value
     *
     * @return string
     */
    public function getGuid(){
      return $this->_get(1);
    }
    
    /**
     * Set <guid> value
     *
     * @param string $value
     * @return \RO\Cmd\SpEffectData
     */
    public function setGuid( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <id> has a value
     *
     * @return boolean
     */
    public function hasId(){
      return $this->_has(2);
    }
    
    /**
     * Clear <id> value
     *
     * @return \RO\Cmd\SpEffectData
     */
    public function clearId(){
      return $this->_clear(2);
    }
    
    /**
     * Get <id> value
     *
     * @return int
     */
    public function getId(){
      return $this->_get(2);
    }
    
    /**
     * Set <id> value
     *
     * @param int $value
     * @return \RO\Cmd\SpEffectData
     */
    public function setId( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <entity> has a value
     *
     * @return boolean
     */
    public function hasEntity(){
      return $this->_has(3);
    }
    
    /**
     * Clear <entity> value
     *
     * @return \RO\Cmd\SpEffectData
     */
    public function clearEntity(){
      return $this->_clear(3);
    }
    
    /**
     * Get <entity> value
     *
     * @param int $idx
     * @return int
     */
    public function getEntity($idx = NULL){
      return $this->_get(3, $idx);
    }
    
    /**
     * Set <entity> value
     *
     * @param int $value
     * @return \RO\Cmd\SpEffectData
     */
    public function setEntity( $value, $idx = NULL){
      return $this->_set(3, $value, $idx);
    }
    
    /**
     * Get all elements of <entity>
     *
     * @return int[]
     */
    public function getEntityList(){
     return $this->_get(3);
    }
    
    /**
     * Add a new element to <entity>
     *
     * @param int $value
     * @return \RO\Cmd\SpEffectData
     */
    public function addEntity( $value){
     return $this->_add(3, $value);
    }
    
    /**
     * Check if <expiretime> has a value
     *
     * @return boolean
     */
    public function hasExpiretime(){
      return $this->_has(4);
    }
    
    /**
     * Clear <expiretime> value
     *
     * @return \RO\Cmd\SpEffectData
     */
    public function clearExpiretime(){
      return $this->_clear(4);
    }
    
    /**
     * Get <expiretime> value
     *
     * @return int
     */
    public function getExpiretime(){
      return $this->_get(4);
    }
    
    /**
     * Set <expiretime> value
     *
     * @param int $value
     * @return \RO\Cmd\SpEffectData
     */
    public function setExpiretime( $value){
      return $this->_set(4, $value);
    }
  }
}

