<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: FuBenCmd.proto

namespace RO\Cmd {

  class StageStepItem extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $stageid = null;
    
    /**  @var int */
    public $stepid = null;
    
    /**  @var int */
    public $type = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.StageStepItem');

      // OPTIONAL UINT32 stageid = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "stageid";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL UINT32 stepid = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "stepid";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL UINT32 type = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "type";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <stageid> has a value
     *
     * @return boolean
     */
    public function hasStageid(){
      return $this->_has(1);
    }
    
    /**
     * Clear <stageid> value
     *
     * @return \RO\Cmd\StageStepItem
     */
    public function clearStageid(){
      return $this->_clear(1);
    }
    
    /**
     * Get <stageid> value
     *
     * @return int
     */
    public function getStageid(){
      return $this->_get(1);
    }
    
    /**
     * Set <stageid> value
     *
     * @param int $value
     * @return \RO\Cmd\StageStepItem
     */
    public function setStageid( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <stepid> has a value
     *
     * @return boolean
     */
    public function hasStepid(){
      return $this->_has(2);
    }
    
    /**
     * Clear <stepid> value
     *
     * @return \RO\Cmd\StageStepItem
     */
    public function clearStepid(){
      return $this->_clear(2);
    }
    
    /**
     * Get <stepid> value
     *
     * @return int
     */
    public function getStepid(){
      return $this->_get(2);
    }
    
    /**
     * Set <stepid> value
     *
     * @param int $value
     * @return \RO\Cmd\StageStepItem
     */
    public function setStepid( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <type> has a value
     *
     * @return boolean
     */
    public function hasType(){
      return $this->_has(3);
    }
    
    /**
     * Clear <type> value
     *
     * @return \RO\Cmd\StageStepItem
     */
    public function clearType(){
      return $this->_clear(3);
    }
    
    /**
     * Get <type> value
     *
     * @return int
     */
    public function getType(){
      return $this->_get(3);
    }
    
    /**
     * Set <type> value
     *
     * @param int $value
     * @return \RO\Cmd\StageStepItem
     */
    public function setType( $value){
      return $this->_set(3, $value);
    }
  }
}

