<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: FuBenCmd.proto

namespace RO\Cmd {

  class SuperGvgSyncFubenCmd extends \DrSlump\Protobuf\Message {

    /**  @var int - \RO\Cmd\Command */
    public $cmd = \RO\Cmd\Command::FUBEN_PROTOCMD;
    
    /**  @var int - \RO\Cmd\FuBenParam */
    public $param = \RO\Cmd\FuBenParam::SUPERGVG_INFO_SYNC;
    
    /**  @var \RO\Cmd\GvgTowerData[]  */
    public $towers = array();
    
    /**  @var \RO\Cmd\GvgGuildInfo[]  */
    public $guildinfo = array();
    
    /**  @var int */
    public $firebegintime = 0;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.SuperGvgSyncFubenCmd');

      // OPTIONAL ENUM cmd = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "cmd";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\Command';
      $f->default   = \RO\Cmd\Command::FUBEN_PROTOCMD;
      $descriptor->addField($f);

      // OPTIONAL ENUM param = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "param";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\RO\Cmd\FuBenParam';
      $f->default   = \RO\Cmd\FuBenParam::SUPERGVG_INFO_SYNC;
      $descriptor->addField($f);

      // REPEATED MESSAGE towers = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "towers";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\RO\Cmd\GvgTowerData';
      $descriptor->addField($f);

      // REPEATED MESSAGE guildinfo = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "guildinfo";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\RO\Cmd\GvgGuildInfo';
      $descriptor->addField($f);

      // OPTIONAL UINT32 firebegintime = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "firebegintime";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->default   = 0;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <cmd> has a value
     *
     * @return boolean
     */
    public function hasCmd(){
      return $this->_has(1);
    }
    
    /**
     * Clear <cmd> value
     *
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function clearCmd(){
      return $this->_clear(1);
    }
    
    /**
     * Get <cmd> value
     *
     * @return int - \RO\Cmd\Command
     */
    public function getCmd(){
      return $this->_get(1);
    }
    
    /**
     * Set <cmd> value
     *
     * @param int - \RO\Cmd\Command $value
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function setCmd( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <param> has a value
     *
     * @return boolean
     */
    public function hasParam(){
      return $this->_has(2);
    }
    
    /**
     * Clear <param> value
     *
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function clearParam(){
      return $this->_clear(2);
    }
    
    /**
     * Get <param> value
     *
     * @return int - \RO\Cmd\FuBenParam
     */
    public function getParam(){
      return $this->_get(2);
    }
    
    /**
     * Set <param> value
     *
     * @param int - \RO\Cmd\FuBenParam $value
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function setParam( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <towers> has a value
     *
     * @return boolean
     */
    public function hasTowers(){
      return $this->_has(3);
    }
    
    /**
     * Clear <towers> value
     *
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function clearTowers(){
      return $this->_clear(3);
    }
    
    /**
     * Get <towers> value
     *
     * @param int $idx
     * @return \RO\Cmd\GvgTowerData
     */
    public function getTowers($idx = NULL){
      return $this->_get(3, $idx);
    }
    
    /**
     * Set <towers> value
     *
     * @param \RO\Cmd\GvgTowerData $value
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function setTowers(\RO\Cmd\GvgTowerData $value, $idx = NULL){
      return $this->_set(3, $value, $idx);
    }
    
    /**
     * Get all elements of <towers>
     *
     * @return \RO\Cmd\GvgTowerData[]
     */
    public function getTowersList(){
     return $this->_get(3);
    }
    
    /**
     * Add a new element to <towers>
     *
     * @param \RO\Cmd\GvgTowerData $value
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function addTowers(\RO\Cmd\GvgTowerData $value){
     return $this->_add(3, $value);
    }
    
    /**
     * Check if <guildinfo> has a value
     *
     * @return boolean
     */
    public function hasGuildinfo(){
      return $this->_has(4);
    }
    
    /**
     * Clear <guildinfo> value
     *
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function clearGuildinfo(){
      return $this->_clear(4);
    }
    
    /**
     * Get <guildinfo> value
     *
     * @param int $idx
     * @return \RO\Cmd\GvgGuildInfo
     */
    public function getGuildinfo($idx = NULL){
      return $this->_get(4, $idx);
    }
    
    /**
     * Set <guildinfo> value
     *
     * @param \RO\Cmd\GvgGuildInfo $value
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function setGuildinfo(\RO\Cmd\GvgGuildInfo $value, $idx = NULL){
      return $this->_set(4, $value, $idx);
    }
    
    /**
     * Get all elements of <guildinfo>
     *
     * @return \RO\Cmd\GvgGuildInfo[]
     */
    public function getGuildinfoList(){
     return $this->_get(4);
    }
    
    /**
     * Add a new element to <guildinfo>
     *
     * @param \RO\Cmd\GvgGuildInfo $value
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function addGuildinfo(\RO\Cmd\GvgGuildInfo $value){
     return $this->_add(4, $value);
    }
    
    /**
     * Check if <firebegintime> has a value
     *
     * @return boolean
     */
    public function hasFirebegintime(){
      return $this->_has(5);
    }
    
    /**
     * Clear <firebegintime> value
     *
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function clearFirebegintime(){
      return $this->_clear(5);
    }
    
    /**
     * Get <firebegintime> value
     *
     * @return int
     */
    public function getFirebegintime(){
      return $this->_get(5);
    }
    
    /**
     * Set <firebegintime> value
     *
     * @param int $value
     * @return \RO\Cmd\SuperGvgSyncFubenCmd
     */
    public function setFirebegintime( $value){
      return $this->_set(5, $value);
    }
  }
}

