<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: SceneItem.proto

namespace RO\Cmd {

  class TradeComposePair extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $compose_id = null;
    
    /**  @var int */
    public $count = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.TradeComposePair');

      // OPTIONAL UINT32 compose_id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "compose_id";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL UINT32 count = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "count";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <compose_id> has a value
     *
     * @return boolean
     */
    public function hasComposeId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <compose_id> value
     *
     * @return \RO\Cmd\TradeComposePair
     */
    public function clearComposeId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <compose_id> value
     *
     * @return int
     */
    public function getComposeId(){
      return $this->_get(1);
    }
    
    /**
     * Set <compose_id> value
     *
     * @param int $value
     * @return \RO\Cmd\TradeComposePair
     */
    public function setComposeId( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <count> has a value
     *
     * @return boolean
     */
    public function hasCount(){
      return $this->_has(2);
    }
    
    /**
     * Clear <count> value
     *
     * @return \RO\Cmd\TradeComposePair
     */
    public function clearCount(){
      return $this->_clear(2);
    }
    
    /**
     * Get <count> value
     *
     * @return int
     */
    public function getCount(){
      return $this->_get(2);
    }
    
    /**
     * Set <count> value
     *
     * @param int $value
     * @return \RO\Cmd\TradeComposePair
     */
    public function setCount( $value){
      return $this->_set(2, $value);
    }
  }
}

