<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin @package_version@
// Source: Tutor.proto

namespace RO\Cmd {

  class TutorReward extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $charid = 0;
    
    /**  @var string */
    public $name = null;
    
    /**  @var int[]  */
    public $reward = array();
    
    /**  @var \RO\Cmd\TutorRewardItem[]  */
    public $item = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'Cmd.TutorReward');

      // OPTIONAL UINT64 charid = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "charid";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->default   = 0;
      $descriptor->addField($f);

      // OPTIONAL STRING name = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "name";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED UINT32 reward = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "reward";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      // REPEATED MESSAGE item = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "item";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\RO\Cmd\TutorRewardItem';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <charid> has a value
     *
     * @return boolean
     */
    public function hasCharid(){
      return $this->_has(1);
    }
    
    /**
     * Clear <charid> value
     *
     * @return \RO\Cmd\TutorReward
     */
    public function clearCharid(){
      return $this->_clear(1);
    }
    
    /**
     * Get <charid> value
     *
     * @return int
     */
    public function getCharid(){
      return $this->_get(1);
    }
    
    /**
     * Set <charid> value
     *
     * @param int $value
     * @return \RO\Cmd\TutorReward
     */
    public function setCharid( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <name> has a value
     *
     * @return boolean
     */
    public function hasName(){
      return $this->_has(2);
    }
    
    /**
     * Clear <name> value
     *
     * @return \RO\Cmd\TutorReward
     */
    public function clearName(){
      return $this->_clear(2);
    }
    
    /**
     * Get <name> value
     *
     * @return string
     */
    public function getName(){
      return $this->_get(2);
    }
    
    /**
     * Set <name> value
     *
     * @param string $value
     * @return \RO\Cmd\TutorReward
     */
    public function setName( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <reward> has a value
     *
     * @return boolean
     */
    public function hasReward(){
      return $this->_has(3);
    }
    
    /**
     * Clear <reward> value
     *
     * @return \RO\Cmd\TutorReward
     */
    public function clearReward(){
      return $this->_clear(3);
    }
    
    /**
     * Get <reward> value
     *
     * @param int $idx
     * @return int
     */
    public function getReward($idx = NULL){
      return $this->_get(3, $idx);
    }
    
    /**
     * Set <reward> value
     *
     * @param int $value
     * @return \RO\Cmd\TutorReward
     */
    public function setReward( $value, $idx = NULL){
      return $this->_set(3, $value, $idx);
    }
    
    /**
     * Get all elements of <reward>
     *
     * @return int[]
     */
    public function getRewardList(){
     return $this->_get(3);
    }
    
    /**
     * Add a new element to <reward>
     *
     * @param int $value
     * @return \RO\Cmd\TutorReward
     */
    public function addReward( $value){
     return $this->_add(3, $value);
    }
    
    /**
     * Check if <item> has a value
     *
     * @return boolean
     */
    public function hasItem(){
      return $this->_has(4);
    }
    
    /**
     * Clear <item> value
     *
     * @return \RO\Cmd\TutorReward
     */
    public function clearItem(){
      return $this->_clear(4);
    }
    
    /**
     * Get <item> value
     *
     * @param int $idx
     * @return \RO\Cmd\TutorRewardItem
     */
    public function getItem($idx = NULL){
      return $this->_get(4, $idx);
    }
    
    /**
     * Set <item> value
     *
     * @param \RO\Cmd\TutorRewardItem $value
     * @return \RO\Cmd\TutorReward
     */
    public function setItem(\RO\Cmd\TutorRewardItem $value, $idx = NULL){
      return $this->_set(4, $value, $idx);
    }
    
    /**
     * Get all elements of <item>
     *
     * @return \RO\Cmd\TutorRewardItem[]
     */
    public function getItemList(){
     return $this->_get(4);
    }
    
    /**
     * Add a new element to <item>
     *
     * @param \RO\Cmd\TutorRewardItem $value
     * @return \RO\Cmd\TutorReward
     */
    public function addItem(\RO\Cmd\TutorRewardItem $value){
     return $this->_add(4, $value);
    }
  }
}

